# Generated by Django 2.2.16 on 2022-01-11 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(
                default='No name', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='No slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(
                default='No name', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='No slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='category', to='reviews.Category', verbose_name='Категория произведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(
                blank=True, verbose_name='Описание произведения'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='genre', to='reviews.Genre', verbose_name='Жанр произведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(
                default='No name', max_length=250, verbose_name='Название произведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Рейтинг произведения'),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, validators=[
                                                   django.core.validators.MaxValueValidator(2022)], verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
